#define BUILD_COMMIT_ID "0.1-gd354761"
#define PROJECT_VERSION "1.1.0"
#define PROJECT_VERSION_BUILD_NO "24"
#define PROJECT_VERSION_LONG PROJECT_VERSION "." PROJECT_VERSION_BUILD_NO " (" BUILD_COMMIT_ID ")"
